title: Adri√°n Lomas
description: My Android developer blog

url: http://glomadrian.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 # - title: About
 #   url: /about
 # - title: Contact
 #   url: /contact

social:
   github: glomadrian
   twitter: glomadrian
   email: glomadrian@gmail.com

google_analytics: "UA-58263416-1"
